set -g mouse on   # Enable mouse support
setw -g mode-keys vi  # Enable Vi key bindings
set-option -g default-terminal "screen-256color"
set -g base-index 1       # Window numbering starts at 1
setw -g pane-base-index 1 # Pane numbering starts at 1 (optional, but consistent)
set -g history-limit 100000
set -g escape-time 10
set-option -g focus-events on
set-option -g set-clipboard on

# Use system clipboard (requires xclip)
# Copy to system clipboard with 'y' in copy-mode
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

